[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "LPDB_python"
dynamic = ["version"]
requires-python = ">= 3.12"
readme = "README.md"
license = "MIT"

[tool.pytest.ini_options]
pythonpath = [
    "src"
]
